version: '3'

services:
  database:
    image: mysql:8
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '13306:3306'
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
volumes:
  db-store:
